[package]
name = "person"
version = "0.1.0"
authors = ["marioaldairsr <77013992+marioaldairsr@users.noreply.github.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.73"
